server:
    port: 8088
spring:
    application:
        name: wasd
    datasource:
        hikari:
            maximum-pool-size: 4
        url: ${psql.url}
        username: ${psql.username}
        password: ${psql.password}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
    data:
        mongodb:
            uri: ${mongo.uri}
    thymeleaf:
        cache: false
        check-template-location: true
        enabled: true
        prefix: classpath:/templates
        suffix: .html
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: ${kakao.client-id}
                        client-secret: ${kakao.client-secret}
                        client-authentication-method: client_secret_post
                        redirect-uri: http://localhost:8088/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        client-name: kakao
                        scope:
                            - profile_nickname
                            - profile_image
                            - account_email
                    naver:
                        client-id: ${naver.client-id}
                        client-secret: ${naver.client-secret}
                        client-authentication-method: client_secret_post
                        redirect-uri: http://localhost:8088/login/oauth2/code/naver
                        authorization-grant-type: authorization_code
                        client-name: naver
                        scope:
                            - profile
                            - email
                    google:
                        client-id: ${google.client-id}
                        client-secret: ${google.client-secret}
                        scope:
                            - profile
                            - email
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
