server:
    port: 8088
spring:
    application:
        name: wasd
    datasource:
        hikari:
            maximum-pool-size: 4
        url: ${psql.url}
        username: ${psql.username}
        password: ${psql.password}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
    data:
        mongodb:
            host: ${mongo.host}
            port: 27017
            authentication-database: admin
            username: wasd
            password: ${mongo.password}
            database: wasd
    thymeleaf:
        cache: false
        check-template-location: true
        enabled: true
        prefix: classpath:/templates
        suffix: .html
