name: Feature Request
description: 새로운 기능에 대한 제안 요청
labels: [✨feat]
title: '[FEAT] '
body:
  - type: textarea
    id: description
    attributes:
      description: 원하시는 기능을 설명해주세요.
      label: Description
    validations:
      required: true

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      placeholder: 기능을 구현하기 위한 방법이나 기술 스택이 있다면 적어주세요!
    validations:
      required: false